version: '3.8'

services:
  app-backend:
    build: .
    container_name: farmacia-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/farmacia_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1104
    depends_on:
      - postgres-db
    networks:
      - farmacia-network
    restart: always

  postgres-db:
    image: postgres:15
    container_name: farmacia-db
    environment:
      - POSTGRES_DB=farmacia_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1104
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - farmacia-network
    restart: always

networks:
  farmacia-network:
    driver: bridge

volumes:
  postgres-data:
